CBV-64 Added styling to landing page
alanperezse/can_bus_visualizer pull request #27
Opened 2022-09-27 03:28 UTC by christiancordova107

![image](https://user-images.githubusercontent.com/90012330/192424987-12be5261-33eb-42e2-a948-6c953361f524.png)

2022-09-27 18:08 UTC, alanperezse requested changes

2022-09-27 18:08 UTC, alanperezse commented on src/entrypoint/index.tsx
> +        <div className='task' style={{
You should put the styling on the `index.css` file as opposed to the .tsx file

2022-09-27 18:08 UTC, matchagreen commented on src/entrypoint/index.tsx
> +            backgroundImage: `url(${tankBluePrint})`,
The while lines in the tank distract too much from the foreground. Try dimming the image down.

2022-09-28 03:53 UTC, christiancordova107 commented
![image](https://user-images.githubusercontent.com/90012330/192683769-7f0e5f39-7b0e-4ae7-99bf-d8a86a8be649.png)
new background image

2022-09-28 15:03 UTC, alanperezse requested changes
Are we using the tank image for anything else? if not we should remove it before merging

2022-09-28 15:03 UTC, alanperezse commented on src/entrypoint/index.tsx
>                  <i style={{ paddingRight: "10px" }}
You should be moving the style to the css file

2022-09-29 17:05 UTC, alanperezse approved these changes

2022-09-29 17:08 UTC, garciagitmauricio approved these changes

2022-09-29 17:09 UTC, merged